### ISSUE TITLE
Single loop traning

### ISSUE THREAD

**Issue by sulantha2006** [naoto0804/pytorch-VAT#3]
Is there a reason for using a single loop training model compared to a
```
   for epoch in range(n_epochs):
       for iter in range(n_iters):
           train.....
```
I understand that it may not be trivial to get the number of iterations when there are two data loaders with different sizes of samples. But any explanation is really appreciated.

**Comment by naoto0804** [comment]
Thanks for visiting this repo! 
It's just a personal preference;
Maybe I just preferred shallower indentation, and I could not come up with some module that is triggered in a epoch-wise manner when I wrote this code.
